#!/bin/bash

# berlinix, get pthread_xxx function prototype from man page
# method: man pthread_xxx | col -b | sed ...

api_list=(
pthread_atfork
pthread_atfork_np
pthread_attr_destroy
pthread_attr_getdetachstate
pthread_attr_getinheritsched
pthread_attr_getschedparam
pthread_attr_getschedpolicy
pthread_attr_getscope
pthread_attr_getstackaddr
pthread_attr_getstacksize
pthread_attr_init
pthread_attr_setdetachstate
pthread_attr_setinheritsched
pthread_attr_setschedparam
pthread_attr_setschedpolicy
pthread_attr_setscope
pthread_attr_setstackaddr
pthread_attr_setstacksize
pthread_cancel
pthread_cleanup_peek_np
pthread_cleanup_pop
pthread_cleanup_push
pthread_clear_exit_np
pthread_cond_broadcast
pthread_cond_destroy
pthread_cond_init
pthread_cond_signal
pthread_cond_timedwait
pthread_cond_wait
pthread_condattr_destroy
pthread_condattr_init
pthread_condattr_getpshared
pthread_condattr_setpshared
pthread_create
pthread_delay_np
pthread_detach
pthread_equal
pthread_exit
pthread_extendedjoin_np
pthread_get_expiration_np
pthread_getcancelstate_np
pthread_getconcurrency
pthread_getpthreadoption_np
pthread_getschedparam
pthread_getspecific
pthread_getthreadid_np
pthread_getunique_np
pthread_is_initialthread_np
pthread_is_multithreaded_np
pthread_join
pthread_join_np
pthread_key_create
pthread_key_delete
pthread_kill
pthread_lock_global_np
pthread_mutex_destroy
pthread_mutex_getprioceiling
pthread_mutex_init
pthread_mutex_lock
pthread_mutex_setprioceiling
pthread_mutex_timedlock_np
pthread_mutex_trylock
pthread_mutex_unlock
pthread_mutexattr_destroy
pthread_mutexattr_getkind_np
pthread_mutexattr_getname_np
pthread_mutexattr_getprioceiling
pthread_mutexattr_getprotocol
pthread_mutexattr_getpshared
pthread_mutexattr_gettype
pthread_mutexattr_init
pthread_mutexattr_setkind_np
pthread_mutexattr_setname_np
pthread_mutexattr_setprioceiling
pthread_mutexattr_setprotocol
pthread_mutexattr_setpshared
pthread_mutexattr_settype
pthread_once
pthread_rwlock_destroy
pthread_rwlock_init
pthread_rwlock_rdlock
pthread_rwlock_timedrdlock_np
pthread_rwlock_timedwrlock_np
pthread_rwlock_tryrdlock
pthread_rwlock_trywrlock
pthread_rwlock_unlock
pthread_rwlock_wrlock
pthread_rwlockattr_destroy
pthread_rwlockattr_getpshared
pthread_rwlockattr_init
pthread_rwlockattr_setpshared
pthread_self
pthread_set_mutexattr_default_np
pthread_setcancelstate
pthread_setcanceltype
pthread_setconcurrency
pthread_setpthreadoption_np
pthread_setschedparam
pthread_setspecific
pthread_sigmask
pthread_signal_to_cancel_np
pthread_test_exit_np
pthread_testcancel
pthread_trace_init_np
PTHREAD_TRACE_NP
pthread_unlock_global_np
sched_yield
)

for a in ${api_list[@]}; do 
    man $a 2>/dev/null | col -b | sed '/SYN/,/DESC/!d' | sed '/SYNOPSIS/,/DESCRIPTION/!d' | sed '/int/,/;$/!d'
done

# test

#man pthread_create|col -b|sed '/SYN/,/DESC/!d'|sed '/int/,/;$/!d'
#man pthread_setcancelstate|col -b|sed '/SYN/,/DESC/!d'|sed '/SYNOPSIS/,/DESCRIPTION/!d'|sed '/int/,/;$/!d'
